-- [DB_SCALES].[SSCCSTORAGE]
-- бепяхъ 0.0.10
USE [SCALESDB]
SELECT
	 [DB_SCALES].[SSCCSTORAGE].[GLN]
	,[DB_SCALES].[SSCCSTORAGE].[COUNTER]
FROM [DB_SCALES].[SSCCSTORAGE]
ORDER BY [DB_SCALES].[SSCCSTORAGE].[GLN]

-- [DB_SSCC].[SSCCSTORAGE]
-- бепяхъ 0.0.10
USE [SCALESDB]
SELECT
	 [DB_SSCC].[SSCCSTORAGE].[GLN]
	,[DB_SSCC].[SSCCSTORAGE].[COUNTER]
FROM [DB_SSCC].[SSCCSTORAGE]
ORDER BY [DB_SSCC].[SSCCSTORAGE].[GLN]
