-- Table Scales
use [ScalesDB]
select
	 [Id]
	,[CreateDate]
	,[ModifiedDate]
	,[OrganizationId]
	,[Description]
	,[DeviceIP]
	,[DevicePort]
	,[DeviceMAC]
	,[DeviceSendTimeout]
	,[DeviceReceiveTimeout]
	,[DeviceComPort]
	,[ZebraIP]
	,[ZebraPort]
	,[UseOrder]
	,[VerScalesUI]
	,[DeviceNumber]
	,[TemplateIdDefault]
	,[TemplateIdSeries]
	,[ScaleFactor]
	,[Marked]
	,[HostId]
from [db_scales].[Scales]
order by [Id]
