-- Table Scales
select
	 [Id]
	,[CreateDate]
	,[ModifiedDate]
	,[OrganizationId]
	,[Description]
	,[DeviceIP]
	,[DevicePort]
	,[DeviceMAC]
	,[DeviceSendTimeout]
	,[DeviceReceiveTimeout]
	,[DeviceComPort]
	,[ZebraIP]
	,[ZebraPort]
	,[UseOrder]
	,[VerScalesUI]
	,[DeviceNumber]
	,[TemplateIdDefault]
	,[TemplateIdSeries]
	,[ScaleFactor]
	,[Marked]
	,[HostId]
	,[lt].[ICON]
from [db_scales].[Scales] [s]
left join [db_scales].[LOG_TYPES] [lt] on [lt].[NUMBER]=[s].[LOG_TYPE]
order by [Id]
