-- Table [Scales]
select
	 [s].[Id]
	,[s].[CreateDate]
	,[s].[ModifiedDate]
	,[s].[OrganizationId]
	,[s].[Description]
	,[s].[DeviceIP]
	,[s].[DevicePort]
	,[s].[DeviceMAC]
	,[s].[DeviceSendTimeout]
	,[s].[DeviceReceiveTimeout]
	,[s].[DeviceComPort]
	,[s].[ZebraIP]
	,[s].[ZebraPort]
	,[s].[UseOrder]
	,[s].[VerScalesUI]
	,[s].[DeviceNumber]
	,[s].[TemplateIdDefault]
	,[s].[TemplateIdSeries]
	,[s].[ScaleFactor]
	,[s].[Marked]
	,[s].[HostId]
	,[lt].[ICON]
from [db_scales].[Scales] [s]
left join [db_scales].[LOG_TYPES] [lt] on [lt].[UID]=[s].[LOG_TYPE_UID]
order by [Id]
