-- Таблица BarCodes
select
	 [BarCodes].[Id]
	,[BarCodes].[CreateDate]
	,[BarCodes].[ModifiedDate]
	,[BarCodes].[BarCodeTypeId]
	,[BarCodeTypes].[Name] [BarCodeTypes_Name]
	,[BarCodes].[NomenclatureId]
	,[Nomenclature].[Name] [Nomenclature_Name]
	,[BarCodes].[NomenclatureUnitId]
	,[NomenclatureUnits].[Name] [NomenclatureUnits_Name]
	,[BarCodes].[ContragentId]
	,[Contragents].[Name] [Contragents_Name]
	,[BarCodes].[Value]
from [db_scales].[BarCodes]
left join [db_scales].[BarCodeTypes] on [db_scales].[BarCodes].[BarCodeTypeId]=[db_scales].[BarCodeTypes].[Id]
left join [db_scales].[Nomenclature] on [db_scales].[BarCodes].[NomenclatureId]=[db_scales].[Nomenclature].[Id]
left join [db_scales].[NomenclatureUnits] on [db_scales].[BarCodes].[NomenclatureUnitId]=[db_scales].[NomenclatureUnits].[Id]
left join [db_scales].[Contragents] on [db_scales].[BarCodes].[ContragentId]=[db_scales].[Contragents].[Id]
order by [BarCodes].[Id]
