-- Таблица [Hosts]
select [ID]
      ,[CreateDate]
      ,[ModifiedDate]
      ,[NAME]
      ,[IP]
      ,[MAC]
      ,[IdRRef]
      ,[MARKED]
      ,[SettingsFile]
      ,[IS_DEBUG]
from [db_scales].[Hosts]
