-- Get busy hosts
select [h].[Id]
      ,[h].[CreateDate]
      ,[h].[ModifiedDate]
      ,[h].[Name]
      ,[s].[Id] [Scale_Id]
      ,[s].[Description] [Scale_Description]
      ,[h].[IP]
      ,[h].[MAC]
      ,[h].[IdRRef]
      ,[h].[Marked]
      ,[h].[SettingsFile]
from [db_scales].[Hosts] [h]
left join [db_scales].[Scales] [s] on [h].[Id] = [s].[HostId]
where [h].[Id] in (select [HostId] from [db_scales].[Scales] where [Scales].[HostId] is not null ) 
order by [h].[Name]
