CREATE VIEW [DW].[vwDimContragents]
AS 
SELECT [Marked]
      ,[Code]
      ,[Name]
      ,[FullName]
      ,[IsBuyer]
      ,[IsSupplier]
      ,[GLN]
      ,[GUID_Mercury]
      ,[INN]
      ,[KPP]
      ,[Comment]
      ,[Parents]
      ,[OKPO]
      ,[ContragentType]
      ,[ContactInfo]
      ,[ManagerID]
      ,[ConsolidatedClientID]
      ,[NumberDebtDays]
      ,[AmountDue]
      ,[DaysDeferment]
      ,[CommercialNetworkID]
      ,[CommercialNetworkName]
      ,[ID]
      ,[CreateDate]
      ,[DLM]
      ,[StatusID]
      ,[InformationSystemID]
      ,[CodeInIS]
  FROM [DW].[DimContragents]
