using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
[assembly: InternalsVisibleTo("ScalesUITests")]
[assembly: AssemblyTitle("ScalesUI")]
[assembly: AssemblyDescription("Печать этикеток")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Владимирский стандарт")]
[assembly: AssemblyProduct("WeightService")]
[assembly: AssemblyCopyright("Copyright © 2020 - 2023")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("7be2ce0f-d6d7-4851-b0f1-955381371454")]
[assembly: AssemblyVersion("1.1.5.0")]
[assembly: AssemblyFileVersion("1.1.5.0")]
