-- юрпхасрш
-- бепяхъ 0.0.10
USE [SCALESDB]
SELECT
	 [DB_SCALES].[ATTRIBUTEDEFINATIONLIST].[ID]
	,[DB_SCALES].[ATTRIBUTEDEFINATIONLIST].[ATTDEFDESCRIPTION]
	,[DB_SCALES].[ATTRIBUTEDEFINATIONLIST].[CODE]
	,[DB_SCALES].[ATTRIBUTEDEFINATIONLIST].[DEFAULTVALUE]
	,[DB_SCALES].[ATTRIBUTEDEFINATIONLIST].[NOTES]
FROM [DB_SCALES].[ATTRIBUTEDEFINATIONLIST]
ORDER BY [DB_SCALES].[ATTRIBUTEDEFINATIONLIST].[ID]
