-- гмювемхъ юрпхасрнб
-- бепяхъ 0.0.10
USE [SCALESDB]
SELECT
	 [DB_SCALES].[ATTRIBUTEVALUES].[ID]
	,[DB_SCALES].[ATTRIBUTEVALUES].[ATTRDEFINIONID]
	,[DB_SCALES].[ATTRIBUTEVALUES].[ORDERID]
	,[DB_SCALES].[ATTRIBUTEVALUES].[ORDERID]
FROM [DB_SCALES].[ATTRIBUTEVALUES]
ORDER BY [DB_SCALES].[ATTRIBUTEVALUES].[ID]
