-- беяю.
-- бепяхъ 0.0.10.
USE [SCALESDB]
SELECT
	 [DB_SCALES].[WEITHINGFACT].[ID]
	,[DB_SCALES].[WEITHINGFACT].[PLU]
	,[DB_SCALES].[WEITHINGFACT].[SCALEID]
	,[DB_SCALES].[WEITHINGFACT].[ORDERID]
	,[DB_SCALES].[WEITHINGFACT].[SSCC]
	,[DB_SCALES].[WEITHINGFACT].[WEITHINGDATE]
	,[DB_SCALES].[WEITHINGFACT].[NETWEIGHT]
	,[DB_SCALES].[WEITHINGFACT].[TAREWEIGHT]
	,[DB_SCALES].[WEITHINGFACT].[UUID]
FROM [DB_SCALES].[WEITHINGFACT]
ORDER BY [DB_SCALES].[WEITHINGFACT].[ID]
