-- ярюрсяш гюйюгнб.
-- бепяхъ 0.0.10
USE [SCALESDB]
SELECT
	 [DB_SCALES].[ORDERSTATUS].[ID]
	,[DB_SCALES].[ORDERSTATUS].[ORDERID]
	,[DB_SCALES].[ORDERSTATUS].[CURRENTDATE]
	,[DB_SCALES].[ORDERSTATUS].[CURRENTSTATUS]
FROM [DB_SCALES].[ORDERSTATUS]
ORDER BY [DB_SCALES].[ORDERSTATUS].[ID]
