-- пеяспяш ьюакнмнб.
-- бепяхъ 0.0.10.
USE [SCALESDB]
SELECT
	 [DB_SCALES].[TEMPLATERESOURCES].[ID]
	,[DB_SCALES].[TEMPLATERESOURCES].[TEMPLATEID]
	,[DB_SCALES].[TEMPLATERESOURCES].[NAME]
	,[DB_SCALES].[TEMPLATERESOURCES].[TYPE]
	,[DB_SCALES].[TEMPLATERESOURCES].[IMAGEDATA]
FROM [DB_SCALES].[TEMPLATERESOURCES]
ORDER BY [DB_SCALES].[TEMPLATERESOURCES].[ID]
