//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScalesDesktop.Features.Labels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LabelsResources_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelsResources_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScalesDesktop.Features.Labels.Resources.LabelsResources.en-US", typeof(LabelsResources_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available in.
        /// </summary>
        internal static string BtnCooldown {
            get {
                return ResourceManager.GetString("BtnCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string BtnEnter {
            get {
                return ResourceManager.GetString("BtnEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print label.
        /// </summary>
        internal static string BtnLabelPrint {
            get {
                return ResourceManager.GetString("BtnLabelPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate scale.
        /// </summary>
        internal static string BtnScaleCalibration {
            get {
                return ResourceManager.GetString("BtnScaleCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PLU.
        /// </summary>
        internal static string DisplayPluSelectWarning {
            get {
                return ResourceManager.GetString("DisplayPluSelectWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scales are disconnected.
        /// </summary>
        internal static string DisplayScalesDisconnectedWarning {
            get {
                return ResourceManager.GetString("DisplayScalesDisconnectedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label config.
        /// </summary>
        internal static string LabelConfigHeader {
            get {
                return ResourceManager.GetString("LabelConfigHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesting is not setted.
        /// </summary>
        internal static string NestingSelectPlaceholder {
            get {
                return ResourceManager.GetString("NestingSelectPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLU select.
        /// </summary>
        internal static string PluSelectHeader {
            get {
                return ResourceManager.GetString("PluSelectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select plu.
        /// </summary>
        internal static string PluSelectPlaceholder {
            get {
                return ResourceManager.GetString("PluSelectPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The printer head is opened.
        /// </summary>
        internal static string PrinterStatusHeadOpen {
            get {
                return ResourceManager.GetString("PrinterStatusHeadOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The printer is deactivated.
        /// </summary>
        internal static string PrinterStatusIsDisabled {
            get {
                return ResourceManager.GetString("PrinterStatusIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The printer is offline.
        /// </summary>
        internal static string PrinterStatusIsForceDisconnected {
            get {
                return ResourceManager.GetString("PrinterStatusIsForceDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label is stuck in the printer.
        /// </summary>
        internal static string PrinterStatusPaperJam {
            get {
                return ResourceManager.GetString("PrinterStatusPaperJam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The printer has run out of tape.
        /// </summary>
        internal static string PrinterStatusPaperOut {
            get {
                return ResourceManager.GetString("PrinterStatusPaperOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The printer is on pause.
        /// </summary>
        internal static string PrinterStatusPaused {
            get {
                return ResourceManager.GetString("PrinterStatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown printer error.
        /// </summary>
        internal static string PrinterStatusUnknown {
            get {
                return ResourceManager.GetString("PrinterStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scales lack the necessary weight..
        /// </summary>
        internal static string ScalesStatusTooLight {
            get {
                return ResourceManager.GetString("ScalesStatusTooLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scales are not stable.
        /// </summary>
        internal static string ScalesStatusUnstable {
            get {
                return ResourceManager.GetString("ScalesStatusUnstable", resourceCulture);
            }
        }
    }
}
