//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScalesDesktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResources_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviceControl.Resources.ApplicationResources.en-US", typeof(ApplicationResources_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ActionMenuDelete {
            get {
                return ResourceManager.GetString("ActionMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ActionMenuReset {
            get {
                return ResourceManager.GetString("ActionMenuReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string ActionMenuShare {
            get {
                return ResourceManager.GetString("ActionMenuShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device control.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string ButtonShare {
            get {
                return ResourceManager.GetString("ButtonShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string ContextMenuOpen {
            get {
                return ResourceManager.GetString("ContextMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new tab.
        /// </summary>
        internal static string ContextMenuOpenInNewTab {
            get {
                return ResourceManager.GetString("ContextMenuOpenInNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string DataGridColumnActive {
            get {
                return ResourceManager.GetString("DataGridColumnActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string DataGridColumnAddress {
            get {
                return ResourceManager.GetString("DataGridColumnAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        internal static string DataGridColumnApp {
            get {
                return ResourceManager.GetString("DataGridColumnApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Weight.
        /// </summary>
        internal static string DataGridColumnBoxWeight {
            get {
                return ResourceManager.GetString("DataGridColumnBoxWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string DataGridColumnBrand {
            get {
                return ResourceManager.GetString("DataGridColumnBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle.
        /// </summary>
        internal static string DataGridColumnBundle {
            get {
                return ResourceManager.GetString("DataGridColumnBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change date.
        /// </summary>
        internal static string DataGridColumnChangeDt {
            get {
                return ResourceManager.GetString("DataGridColumnChangeDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip.
        /// </summary>
        internal static string DataGridColumnClip {
            get {
                return ResourceManager.GetString("DataGridColumnClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string DataGridColumnCode {
            get {
                return ResourceManager.GetString("DataGridColumnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM port.
        /// </summary>
        internal static string DataGridColumnCOM {
            get {
                return ResourceManager.GetString("DataGridColumnCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string DataGridColumnCount {
            get {
                return ResourceManager.GetString("DataGridColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        internal static string DataGridColumnCounter {
            get {
                return ResourceManager.GetString("DataGridColumnCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create date.
        /// </summary>
        internal static string DataGridColumnCreateDt {
            get {
                return ResourceManager.GetString("DataGridColumnCreateDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string DataGridColumnData {
            get {
                return ResourceManager.GetString("DataGridColumnData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string DataGridColumnDatabaseTables {
            get {
                return ResourceManager.GetString("DataGridColumnDatabaseTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DataGridColumnDescription {
            get {
                return ResourceManager.GetString("DataGridColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string DataGridColumnDevice {
            get {
                return ResourceManager.GetString("DataGridColumnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device IP.
        /// </summary>
        internal static string DataGridColumnDeviceIp {
            get {
                return ResourceManager.GetString("DataGridColumnDeviceIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string DataGridColumnErrorCounter {
            get {
                return ResourceManager.GetString("DataGridColumnErrorCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        internal static string DataGridColumnExpirationDt {
            get {
                return ResourceManager.GetString("DataGridColumnExpirationDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string DataGridColumnFile {
            get {
                return ResourceManager.GetString("DataGridColumnFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIO.
        /// </summary>
        internal static string DataGridColumnFIO {
            get {
                return ResourceManager.GetString("DataGridColumnFIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string DataGridColumnFirstName {
            get {
                return ResourceManager.GetString("DataGridColumnFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string DataGridColumnFullName {
            get {
                return ResourceManager.GetString("DataGridColumnFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        internal static string DataGridColumnIp {
            get {
                return ResourceManager.GetString("DataGridColumnIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is archival.
        /// </summary>
        internal static string DataGridColumnIsArchival {
            get {
                return ResourceManager.GetString("DataGridColumnIsArchival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is default.
        /// </summary>
        internal static string DataGridColumnIsDefault {
            get {
                return ResourceManager.GetString("DataGridColumnIsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piece.
        /// </summary>
        internal static string DataGridColumnIsPiece {
            get {
                return ResourceManager.GetString("DataGridColumnIsPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string DataGridColumnIsWeight {
            get {
                return ResourceManager.GetString("DataGridColumnIsWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string DataGridColumnLine {
            get {
                return ResourceManager.GetString("DataGridColumnLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Date.
        /// </summary>
        internal static string DataGridColumnLoginDt {
            get {
                return ResourceManager.GetString("DataGridColumnLoginDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Type.
        /// </summary>
        internal static string DataGridColumnLogType {
            get {
                return ResourceManager.GetString("DataGridColumnLogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Temp.
        /// </summary>
        internal static string DataGridColumnMaxTemp {
            get {
                return ResourceManager.GetString("DataGridColumnMaxTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string DataGridColumnMessage {
            get {
                return ResourceManager.GetString("DataGridColumnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Temp.
        /// </summary>
        internal static string DataGridColumnMinTemp {
            get {
                return ResourceManager.GetString("DataGridColumnMinTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DataGridColumnName {
            get {
                return ResourceManager.GetString("DataGridColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string DataGridColumnNumber {
            get {
                return ResourceManager.GetString("DataGridColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string DataGridColumnPassword {
            get {
                return ResourceManager.GetString("DataGridColumnPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronymic.
        /// </summary>
        internal static string DataGridColumnPatronymic {
            get {
                return ResourceManager.GetString("DataGridColumnPatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PcName.
        /// </summary>
        internal static string DataGridColumnPcName {
            get {
                return ResourceManager.GetString("DataGridColumnPcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentages.
        /// </summary>
        internal static string DataGridColumnPercentages {
            get {
                return ResourceManager.GetString("DataGridColumnPercentages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plu.
        /// </summary>
        internal static string DataGridColumnPlu {
            get {
                return ResourceManager.GetString("DataGridColumnPlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plu name.
        /// </summary>
        internal static string DataGridColumnPluName {
            get {
                return ResourceManager.GetString("DataGridColumnPluName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plu number.
        /// </summary>
        internal static string DataGridColumnPluNumber {
            get {
                return ResourceManager.GetString("DataGridColumnPluNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string DataGridColumnPort {
            get {
                return ResourceManager.GetString("DataGridColumnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        internal static string DataGridColumnPrinter {
            get {
                return ResourceManager.GetString("DataGridColumnPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product date.
        /// </summary>
        internal static string DataGridColumnProductDt {
            get {
                return ResourceManager.GetString("DataGridColumnProductDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Site.
        /// </summary>
        internal static string DataGridColumnProductionSite {
            get {
                return ResourceManager.GetString("DataGridColumnProductionSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request message.
        /// </summary>
        internal static string DataGridColumnRequest {
            get {
                return ResourceManager.GetString("DataGridColumnRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request url.
        /// </summary>
        internal static string DataGridColumnRequestUrl {
            get {
                return ResourceManager.GetString("DataGridColumnRequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response message.
        /// </summary>
        internal static string DataGridColumnResponse {
            get {
                return ResourceManager.GetString("DataGridColumnResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string DataGridColumnRoles {
            get {
                return ResourceManager.GetString("DataGridColumnRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row count.
        /// </summary>
        internal static string DataGridColumnRowsCount {
            get {
                return ResourceManager.GetString("DataGridColumnRowsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme.
        /// </summary>
        internal static string DataGridColumnScheme {
            get {
                return ResourceManager.GetString("DataGridColumnScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf life.
        /// </summary>
        internal static string DataGridColumnShelfLifeDays {
            get {
                return ResourceManager.GetString("DataGridColumnShelfLifeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string DataGridColumnSize {
            get {
                return ResourceManager.GetString("DataGridColumnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string DataGridColumnStorage {
            get {
                return ResourceManager.GetString("DataGridColumnStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successes.
        /// </summary>
        internal static string DataGridColumnSuccessCounter {
            get {
                return ResourceManager.GetString("DataGridColumnSuccessCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string DataGridColumnSurname {
            get {
                return ResourceManager.GetString("DataGridColumnSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string DataGridColumnTable {
            get {
                return ResourceManager.GetString("DataGridColumnTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table count.
        /// </summary>
        internal static string DataGridColumnTableCount {
            get {
                return ResourceManager.GetString("DataGridColumnTableCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tare weight.
        /// </summary>
        internal static string DataGridColumnTareWeight {
            get {
                return ResourceManager.GetString("DataGridColumnTareWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string DataGridColumnTemplate {
            get {
                return ResourceManager.GetString("DataGridColumnTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string DataGridColumnTitle {
            get {
                return ResourceManager.GetString("DataGridColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string DataGridColumnType {
            get {
                return ResourceManager.GetString("DataGridColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID.
        /// </summary>
        internal static string DataGridColumnUID {
            get {
                return ResourceManager.GetString("DataGridColumnUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1C UID.
        /// </summary>
        internal static string DataGridColumnUID1C {
            get {
                return ResourceManager.GetString("DataGridColumnUID1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string DataGridColumnVersion {
            get {
                return ResourceManager.GetString("DataGridColumnVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        internal static string DataGridColumnWarehouse {
            get {
                return ResourceManager.GetString("DataGridColumnWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string DataGridColumnWeight {
            get {
                return ResourceManager.GetString("DataGridColumnWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        internal static string DataGridNoResult {
            get {
                return ResourceManager.GetString("DataGridNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total items.
        /// </summary>
        internal static string DataGridTotalItems {
            get {
                return ResourceManager.GetString("DataGridTotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the menu section to continue.
        /// </summary>
        internal static string HomeMsgDescription {
            get {
                return ResourceManager.GetString("HomeMsgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while converting zpl code to image.
        /// </summary>
        internal static string LabelsPreviewErrorMsg {
            get {
                return ResourceManager.GetString("LabelsPreviewErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image.
        /// </summary>
        internal static string LabelsPreviewNoData {
            get {
                return ResourceManager.GetString("LabelsPreviewNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string LabelsPreviewTitle {
            get {
                return ResourceManager.GetString("LabelsPreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1C References.
        /// </summary>
        internal static string Menu1CReferences {
            get {
                return ResourceManager.GetString("Menu1CReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string MenuAdministration {
            get {
                return ResourceManager.GetString("MenuAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string MenuDevices {
            get {
                return ResourceManager.GetString("MenuDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        internal static string MenuDiagnostics {
            get {
                return ResourceManager.GetString("MenuDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string MenuOperations {
            get {
                return ResourceManager.GetString("MenuOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        internal static string MenuReferences {
            get {
                return ResourceManager.GetString("MenuReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1C Logs.
        /// </summary>
        internal static string Section1CLogs {
            get {
                return ResourceManager.GetString("Section1CLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agg. labels.
        /// </summary>
        internal static string SectionAggregatedLabels {
            get {
                return ResourceManager.GetString("SectionAggregatedLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps logs.
        /// </summary>
        internal static string SectionAppsLogs {
            get {
                return ResourceManager.GetString("SectionAppsLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcodes.
        /// </summary>
        internal static string SectionBarcodes {
            get {
                return ResourceManager.GetString("SectionBarcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxes.
        /// </summary>
        internal static string SectionBoxes {
            get {
                return ResourceManager.GetString("SectionBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        internal static string SectionBrands {
            get {
                return ResourceManager.GetString("SectionBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundles.
        /// </summary>
        internal static string SectionBundles {
            get {
                return ResourceManager.GetString("SectionBundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clips.
        /// </summary>
        internal static string SectionClips {
            get {
                return ResourceManager.GetString("SectionClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string SectionDatabase {
            get {
                return ResourceManager.GetString("SectionDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string SectionFormInputEmpty {
            get {
                return ResourceManager.GetString("SectionFormInputEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value....
        /// </summary>
        internal static string SectionFormInputTextPlaceholder {
            get {
                return ResourceManager.GetString("SectionFormInputTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the platform.
        /// </summary>
        internal static string SectionFormPlatformDefaultName {
            get {
                return ResourceManager.GetString("SectionFormPlatformDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer control.
        /// </summary>
        internal static string SectionFormPrinterControl {
            get {
                return ResourceManager.GetString("SectionFormPrinterControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the printer.
        /// </summary>
        internal static string SectionFormPrinterDefaultName {
            get {
                return ResourceManager.GetString("SectionFormPrinterDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relogin.
        /// </summary>
        internal static string SectionFormRelogin {
            get {
                return ResourceManager.GetString("SectionFormRelogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string SectionFormSearch {
            get {
                return ResourceManager.GetString("SectionFormSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        internal static string SectionFormSelectEmpty {
            get {
                return ResourceManager.GetString("SectionFormSelectEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the warehouse.
        /// </summary>
        internal static string SectionFormWarehouseDefaultName {
            get {
                return ResourceManager.GetString("SectionFormWarehouseDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string SectionLabels {
            get {
                return ResourceManager.GetString("SectionLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line PLU.
        /// </summary>
        internal static string SectionLinePLU {
            get {
                return ResourceManager.GetString("SectionLinePLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string SectionLines {
            get {
                return ResourceManager.GetString("SectionLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet Men.
        /// </summary>
        internal static string SectionPalletMen {
            get {
                return ResourceManager.GetString("SectionPalletMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLU.
        /// </summary>
        internal static string SectionPLU {
            get {
                return ResourceManager.GetString("SectionPLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nestrings.
        /// </summary>
        internal static string SectionPluNestings {
            get {
                return ResourceManager.GetString("SectionPluNestings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLU Storages.
        /// </summary>
        internal static string SectionPluStorages {
            get {
                return ResourceManager.GetString("SectionPluStorages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printers.
        /// </summary>
        internal static string SectionPrinters {
            get {
                return ResourceManager.GetString("SectionPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Sites.
        /// </summary>
        internal static string SectionProductionSites {
            get {
                return ResourceManager.GetString("SectionProductionSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string SectionRoles {
            get {
                return ResourceManager.GetString("SectionRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string SectionTemplates {
            get {
                return ResourceManager.GetString("SectionTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates Resources.
        /// </summary>
        internal static string SectionTemplatesResources {
            get {
                return ResourceManager.GetString("SectionTemplatesResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string SectionUsers {
            get {
                return ResourceManager.GetString("SectionUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions.
        /// </summary>
        internal static string SectionVersions {
            get {
                return ResourceManager.GetString("SectionVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouses.
        /// </summary>
        internal static string SectionWarehouses {
            get {
                return ResourceManager.GetString("SectionWarehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weightings.
        /// </summary>
        internal static string SectionWeightings {
            get {
                return ResourceManager.GetString("SectionWeightings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was created.
        /// </summary>
        internal static string ToastAddItem {
            get {
                return ResourceManager.GetString("ToastAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value copied to clipboard.
        /// </summary>
        internal static string ToastCopyToClipboard {
            get {
                return ResourceManager.GetString("ToastCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was deleted.
        /// </summary>
        internal static string ToastDeleteItem {
            get {
                return ResourceManager.GetString("ToastDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original values restored.
        /// </summary>
        internal static string ToastResetItem {
            get {
                return ResourceManager.GetString("ToastResetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was updated.
        /// </summary>
        internal static string ToastUpdateItem {
            get {
                return ResourceManager.GetString("ToastUpdateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url copied to clipboard.
        /// </summary>
        internal static string ToastUrlCopyToClipboard {
            get {
                return ResourceManager.GetString("ToastUrlCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mb.
        /// </summary>
        internal static string UtilsSizeMb {
            get {
                return ResourceManager.GetString("UtilsSizeMb", resourceCulture);
            }
        }
    }
}
