//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScalesHybrid.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResources_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources_ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviceControl.Resources.ApplicationResources.ru-RU", typeof(ApplicationResources_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление Устройствами.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата изменения.
        /// </summary>
        internal static string DataGridColumnChangeDt {
            get {
                return ResourceManager.GetString("DataGridColumnChangeDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во.
        /// </summary>
        internal static string DataGridColumnCount {
            get {
                return ResourceManager.GetString("DataGridColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Счетчик.
        /// </summary>
        internal static string DataGridColumnCounter {
            get {
                return ResourceManager.GetString("DataGridColumnCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        internal static string DataGridColumnCreateDt {
            get {
                return ResourceManager.GetString("DataGridColumnCreateDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устройство.
        /// </summary>
        internal static string DataGridColumnDevice {
            get {
                return ResourceManager.GetString("DataGridColumnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес устройства.
        /// </summary>
        internal static string DataGridColumnDeviceIp {
            get {
                return ResourceManager.GetString("DataGridColumnDeviceIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибок.
        /// </summary>
        internal static string DataGridColumnErrorCounter {
            get {
                return ResourceManager.GetString("DataGridColumnErrorCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Линия.
        /// </summary>
        internal static string DataGridColumnLine {
            get {
                return ResourceManager.GetString("DataGridColumnLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата Входа.
        /// </summary>
        internal static string DataGridColumnLoginDt {
            get {
                return ResourceManager.GetString("DataGridColumnLoginDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        internal static string DataGridColumnName {
            get {
                return ResourceManager.GetString("DataGridColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        internal static string DataGridColumnNumber {
            get {
                return ResourceManager.GetString("DataGridColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принтер.
        /// </summary>
        internal static string DataGridColumnPrinter {
            get {
                return ResourceManager.GetString("DataGridColumnPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url запроса.
        /// </summary>
        internal static string DataGridColumnRequestUrl {
            get {
                return ResourceManager.GetString("DataGridColumnRequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успехи.
        /// </summary>
        internal static string DataGridColumnSuccessCounter {
            get {
                return ResourceManager.GetString("DataGridColumnSuccessCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия.
        /// </summary>
        internal static string DataGridColumnVersion {
            get {
                return ResourceManager.GetString("DataGridColumnVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цех.
        /// </summary>
        internal static string DataGridColumnWorkshop {
            get {
                return ResourceManager.GetString("DataGridColumnWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to всего строк.
        /// </summary>
        internal static string DataGridTotalItems {
            get {
                return ResourceManager.GetString("DataGridTotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите на раздел меню, чтобы продолжить.
        /// </summary>
        internal static string HomeMsgDescription {
            get {
                return ResourceManager.GetString("HomeMsgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные из 1С.
        /// </summary>
        internal static string Menu1CReferences {
            get {
                return ResourceManager.GetString("Menu1CReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрирование.
        /// </summary>
        internal static string MenuAdministration {
            get {
                return ResourceManager.GetString("MenuAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устройства.
        /// </summary>
        internal static string MenuDevices {
            get {
                return ResourceManager.GetString("MenuDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диагностика.
        /// </summary>
        internal static string MenuDiagnostics {
            get {
                return ResourceManager.GetString("MenuDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операции.
        /// </summary>
        internal static string MenuOperations {
            get {
                return ResourceManager.GetString("MenuOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справочник.
        /// </summary>
        internal static string MenuReferences {
            get {
                return ResourceManager.GetString("MenuReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логи 1С.
        /// </summary>
        internal static string Section1CLogs {
            get {
                return ResourceManager.GetString("Section1CLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агр. этикетки.
        /// </summary>
        internal static string SectionAggregatedLabels {
            get {
                return ResourceManager.GetString("SectionAggregatedLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логи приложения.
        /// </summary>
        internal static string SectionAppsLogs {
            get {
                return ResourceManager.GetString("SectionAppsLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Штрихкоды.
        /// </summary>
        internal static string SectionBarcodes {
            get {
                return ResourceManager.GetString("SectionBarcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коробки.
        /// </summary>
        internal static string SectionBoxes {
            get {
                return ResourceManager.GetString("SectionBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бренды.
        /// </summary>
        internal static string SectionBrands {
            get {
                return ResourceManager.GetString("SectionBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пакеты.
        /// </summary>
        internal static string SectionBundles {
            get {
                return ResourceManager.GetString("SectionBundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клипсы.
        /// </summary>
        internal static string SectionClips {
            get {
                return ResourceManager.GetString("SectionClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База данных.
        /// </summary>
        internal static string SectionDatabase {
            get {
                return ResourceManager.GetString("SectionDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хосты.
        /// </summary>
        internal static string SectionHosts {
            get {
                return ResourceManager.GetString("SectionHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этикетки.
        /// </summary>
        internal static string SectionLabels {
            get {
                return ResourceManager.GetString("SectionLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Линии.
        /// </summary>
        internal static string SectionLines {
            get {
                return ResourceManager.GetString("SectionLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платформы.
        /// </summary>
        internal static string SectionPlatforms {
            get {
                return ResourceManager.GetString("SectionPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПЛУ.
        /// </summary>
        internal static string SectionPLU {
            get {
                return ResourceManager.GetString("SectionPLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хранилища ПЛУ.
        /// </summary>
        internal static string SectionPluStorages {
            get {
                return ResourceManager.GetString("SectionPluStorages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принтеры.
        /// </summary>
        internal static string SectionPrinters {
            get {
                return ResourceManager.GetString("SectionPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблоны.
        /// </summary>
        internal static string SectionTemplates {
            get {
                return ResourceManager.GetString("SectionTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресурсы шаблонов.
        /// </summary>
        internal static string SectionTemplatesResources {
            get {
                return ResourceManager.GetString("SectionTemplatesResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        internal static string SectionUsers {
            get {
                return ResourceManager.GetString("SectionUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версии.
        /// </summary>
        internal static string SectionVersions {
            get {
                return ResourceManager.GetString("SectionVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взвешивания.
        /// </summary>
        internal static string SectionWeightings {
            get {
                return ResourceManager.GetString("SectionWeightings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цеха.
        /// </summary>
        internal static string SectionWorkshops {
            get {
                return ResourceManager.GetString("SectionWorkshops", resourceCulture);
            }
        }
    }
}
