//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ws.Shared.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WsDataResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WsDataResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ws.Shared.Resources.WsDataResources", typeof(WsDataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColActive {
            get {
                return ResourceManager.GetString("ColActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColAddress {
            get {
                return ResourceManager.GetString("ColAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColBarcode {
            get {
                return ResourceManager.GetString("ColBarcode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColBarcodeBottom {
            get {
                return ResourceManager.GetString("ColBarcodeBottom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColBarcodeRight {
            get {
                return ResourceManager.GetString("ColBarcodeRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColBarcodeTop {
            get {
                return ResourceManager.GetString("ColBarcodeTop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColBox {
            get {
                return ResourceManager.GetString("ColBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColBoxWeight {
            get {
                return ResourceManager.GetString("ColBoxWeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColBrand {
            get {
                return ResourceManager.GetString("ColBrand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColBundle {
            get {
                return ResourceManager.GetString("ColBundle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColChangeDt {
            get {
                return ResourceManager.GetString("ColChangeDt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColClip {
            get {
                return ResourceManager.GetString("ColClip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColCount {
            get {
                return ResourceManager.GetString("ColCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColCounter {
            get {
                return ResourceManager.GetString("ColCounter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColCreateDt {
            get {
                return ResourceManager.GetString("ColCreateDt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColData {
            get {
                return ResourceManager.GetString("ColData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColDefault {
            get {
                return ResourceManager.GetString("ColDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColDescription {
            get {
                return ResourceManager.GetString("ColDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColDevice {
            get {
                return ResourceManager.GetString("ColDevice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColDt {
            get {
                return ResourceManager.GetString("ColDt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColExpirationDt {
            get {
                return ResourceManager.GetString("ColExpirationDt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColFile {
            get {
                return ResourceManager.GetString("ColFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColFIO {
            get {
                return ResourceManager.GetString("ColFIO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColFirstName {
            get {
                return ResourceManager.GetString("ColFirstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColFullName {
            get {
                return ResourceManager.GetString("ColFullName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColGrossWeight {
            get {
                return ResourceManager.GetString("ColGrossWeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColHeight {
            get {
                return ResourceManager.GetString("ColHeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColKneading {
            get {
                return ResourceManager.GetString("ColKneading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColLabel {
            get {
                return ResourceManager.GetString("ColLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColLine {
            get {
                return ResourceManager.GetString("ColLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColLoginDt {
            get {
                return ResourceManager.GetString("ColLoginDt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColMaxTemp {
            get {
                return ResourceManager.GetString("ColMaxTemp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColMessage {
            get {
                return ResourceManager.GetString("ColMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColMinTemp {
            get {
                return ResourceManager.GetString("ColMinTemp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColName {
            get {
                return ResourceManager.GetString("ColName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColNestingPerBox {
            get {
                return ResourceManager.GetString("ColNestingPerBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColNetWeight {
            get {
                return ResourceManager.GetString("ColNetWeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColNumber {
            get {
                return ResourceManager.GetString("ColNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColPallet {
            get {
                return ResourceManager.GetString("ColPallet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColPalletMan {
            get {
                return ResourceManager.GetString("ColPalletMan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColPalletWeight {
            get {
                return ResourceManager.GetString("ColPalletWeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColPassword {
            get {
                return ResourceManager.GetString("ColPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColPatronymic {
            get {
                return ResourceManager.GetString("ColPatronymic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColPcName {
            get {
                return ResourceManager.GetString("ColPcName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColPercentages {
            get {
                return ResourceManager.GetString("ColPercentages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColPlu {
            get {
                return ResourceManager.GetString("ColPlu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColPluName {
            get {
                return ResourceManager.GetString("ColPluName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColPluNumber {
            get {
                return ResourceManager.GetString("ColPluNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColPluPiece {
            get {
                return ResourceManager.GetString("ColPluPiece", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColPluWeight {
            get {
                return ResourceManager.GetString("ColPluWeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColPort {
            get {
                return ResourceManager.GetString("ColPort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColPrinter {
            get {
                return ResourceManager.GetString("ColPrinter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColProductDt {
            get {
                return ResourceManager.GetString("ColProductDt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColProductionSite {
            get {
                return ResourceManager.GetString("ColProductionSite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColRoles {
            get {
                return ResourceManager.GetString("ColRoles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColScheme {
            get {
                return ResourceManager.GetString("ColScheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColShelfLifeDays {
            get {
                return ResourceManager.GetString("ColShelfLifeDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColSize {
            get {
                return ResourceManager.GetString("ColSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColStatus {
            get {
                return ResourceManager.GetString("ColStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColStorageMethod {
            get {
                return ResourceManager.GetString("ColStorageMethod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColSurname {
            get {
                return ResourceManager.GetString("ColSurname", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColTable {
            get {
                return ResourceManager.GetString("ColTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColTables {
            get {
                return ResourceManager.GetString("ColTables", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColTareWeight {
            get {
                return ResourceManager.GetString("ColTareWeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColTareWeightTotal {
            get {
                return ResourceManager.GetString("ColTareWeightTotal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColTemplate {
            get {
                return ResourceManager.GetString("ColTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColTemplatePiece {
            get {
                return ResourceManager.GetString("ColTemplatePiece", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColTemplateWeight {
            get {
                return ResourceManager.GetString("ColTemplateWeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColTitle {
            get {
                return ResourceManager.GetString("ColTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColType {
            get {
                return ResourceManager.GetString("ColType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColUser {
            get {
                return ResourceManager.GetString("ColUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColVersion {
            get {
                return ResourceManager.GetString("ColVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColWarehouse {
            get {
                return ResourceManager.GetString("ColWarehouse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColWeight {
            get {
                return ResourceManager.GetString("ColWeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColWeightGross {
            get {
                return ResourceManager.GetString("ColWeightGross", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ColWidth {
            get {
                return ResourceManager.GetString("ColWidth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MeasureKg {
            get {
                return ResourceManager.GetString("MeasureKg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MeasureMb {
            get {
                return ResourceManager.GetString("MeasureMb", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MeasureSec {
            get {
                return ResourceManager.GetString("MeasureSec", resourceCulture);
            }
        }
    }
}
