-- Nomenclature. NonNormilize records.
use [VSDWH]
select 
	 [n].[ID]
	,[n].[Code]
	,[n].[Marked]
	,[n].[Name]
	,[n].[Parents]
	,[n].[Article]
	,[n].[Weighted]
	,[n].[GUID_Mercury]
	,[n].[KeepTrackOfCharacteristics]
	,[n].[NameFull]
	,[n].[Comment]
	,[n].[IsService]
	,[n].[IsProduct]
	,[n].[AdditionalDescriptionOfNomenclature]
	,[n].[NomenclatureGroupCost]
	,[n].[NomenclatureGroup]
	,[n].[ArticleCost]
	,[n].[Brand]
	,[n].[NomenclatureType]
	,[n].[VATRate]
	,[n].[Unit]
	,[n].[Weight]
	,[n].[boxTypeID]
	,[n].[boxTypeName]
	,[n].[packTypeID]
	,[n].[packTypeName]
	,[n].[SerializedRepresentationObject]
	,[n].[CreateDate]
	,[n].[DLM]
	,[n].[StatusID]
	,[n].[InformationSystemID]
	,[n].[CodeInIS]
	,[n].[RelevanceStatus]
	,[n].[NormalizationStatus]
	,[n].[MasterId]
from [DW].[DimNomenclatures] [n]
where [n].[MasterId] is null and [IsProduct] = 1 -- and [RelevanceStatus] = 2
order by [n].[Name]
