CREATE VIEW [DW].[vwDimNomenclatures]
	AS SELECT [Code]
      ,[Marked]
      ,[Name]
      ,[Parents]
      ,[Article]
      ,[Weighted]
      ,[GUID_Mercury]
      ,[KeepTrackOfCharacteristics]
      ,[NameFull]
      ,[Comment]
      ,[IsService]
      ,[AdditionalDescriptionOfNomenclature]
      ,[NomenclatureGroupCost]
      ,[NomenclatureGroup]
      ,[ArticleCost]
      ,[Brand]
      ,[NomenclatureType]
      ,[VATRate]
      ,[Unit]
      ,[Weight]
      ,[boxTypeID]
      ,[boxTypeName]
      ,[packTypeID]
      ,[packTypeName]
      ,[ID]
      ,[CreateDate]
      ,[DLM]
      ,[StatusID]
      ,[InformationSystemID]
      ,[CodeInIS]
	FROM [DW].[DimNomenclatures]
