// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ws.Database;

#nullable disable

namespace Ws.Database.Migrations
{
    [DbContext(typeof(WsDbContext))]
    [Migration("20240701131557_Change_NumberType_ToStr_PalletTable")]
    partial class Change_NumberType_ToStr_PalletTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ARMS_PLUS_FK", b =>
                {
                    b.Property<Guid>("PLU_UID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ARM_UID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PLU_UID", "ARM_UID");

                    b.HasIndex("ARM_UID");

                    b.ToTable("ARMS_PLUS_FK");
                });

            modelBuilder.Entity("Ws.Database.Entities.Print.Labels.LabelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<Guid>("ARM_UID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BarcodeBottom")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("BARCODE_BOTTOM");

                    b.Property<string>("BarcodeRight")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("BARCODE_RIGHT");

                    b.Property<string>("BarcodeTop")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("BARCODE_TOP");

                    b.Property<int>("BundleCount")
                        .HasColumnType("int")
                        .HasColumnName("BUNDLE_COUNT");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ExpirationDt")
                        .HasColumnType("datetime2")
                        .HasColumnName("EXPIRATION_DT");

                    b.Property<short>("Kneading")
                        .HasColumnType("smallint")
                        .HasColumnName("KNEADING");

                    b.Property<Guid?>("PLU_UID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PalletEntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PALLET_UID");

                    b.Property<DateTime>("ProductDt")
                        .HasColumnType("datetime2")
                        .HasColumnName("PRODUCT_DT");

                    b.Property<decimal>("WeightNet")
                        .HasPrecision(5, 3)
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("WEIGHT_NET");

                    b.Property<decimal>("WeightTare")
                        .HasPrecision(5, 3)
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("WEIGHT_TARE");

                    b.Property<string>("Zpl")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ZPL");

                    b.HasKey("Id");

                    b.HasIndex("ARM_UID");

                    b.HasIndex("BarcodeTop")
                        .IsUnique()
                        .HasDatabaseName("UQ_LABELS__BARCODE_TOP");

                    b.HasIndex("PLU_UID");

                    b.HasIndex("PalletEntityId");

                    b.ToTable("LABELS", "PRINT");
                });

            modelBuilder.Entity("Ws.Database.Entities.Print.Pallets.PalletEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<Guid>("ARM_UID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("BARCODE");

                    b.Property<long>("Counter")
                        .HasColumnType("bigint")
                        .HasColumnName("COUNTER");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("NUMBER");

                    b.Property<Guid>("PALLET_MAN_UID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ProductDt")
                        .HasColumnType("datetime2")
                        .HasColumnName("PRODUCT_DT");

                    b.Property<decimal>("TrayWeight")
                        .HasPrecision(5, 3)
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("WEIGHT_TRAY");

                    b.HasKey("Id");

                    b.HasIndex("ARM_UID");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("UQ_PALLETS__BARCODE");

                    b.HasIndex("Counter")
                        .IsUnique()
                        .HasDatabaseName("UQ_PALLETS__COUNTER");

                    b.HasIndex("PALLET_MAN_UID");

                    b.ToTable("PALLETS", "PRINT");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref.Lines.LineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<DateTime>("ChangeDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Counter")
                        .HasColumnType("int")
                        .HasColumnName("COUNTER");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("NAME");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("NUMBER");

                    b.Property<Guid>("PRINTER_UID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PcName")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("PC_NAME");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(9)")
                        .HasColumnName("TYPE");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("VERSION");

                    b.Property<Guid>("WAREHOUSE_UID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_ARMS__NAME");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("UQ_ARMS__NUMBER");

                    b.HasIndex("PRINTER_UID");

                    b.HasIndex("PcName")
                        .IsUnique()
                        .HasDatabaseName("UQ_ARMS__PC_NAME");

                    b.HasIndex("WAREHOUSE_UID");

                    b.ToTable("ARMS", "REF");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref.PalletMen.PalletManEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<DateTime>("ChangeDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(4)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("PATRONYMIC");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("SURNAME");

                    b.Property<Guid>("Uid1C")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID_1C");

                    b.Property<Guid>("WAREHOUSE_UID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Uid1C")
                        .IsUnique()
                        .HasDatabaseName("UQ_PALLET_MEN__UID_1C");

                    b.HasIndex("WAREHOUSE_UID");

                    b.HasIndex("Name", "Surname", "Patronymic")
                        .IsUnique()
                        .HasDatabaseName("UQ_PALLET_MEN__FIO");

                    b.ToTable("PALLET_MEN", "REF");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref.Printers.PrinterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<DateTime>("ChangeDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("IP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("NAME");

                    b.Property<Guid>("PRODUCTION_SITE_UID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("TYPE");

                    b.HasKey("Id");

                    b.HasIndex("Ip")
                        .IsUnique()
                        .HasDatabaseName("UQ_PALLET_MEN__IP");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_PRINTERS__NAME");

                    b.HasIndex("PRODUCTION_SITE_UID");

                    b.ToTable("PRINTERS", "REF");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref.ProductionSites.ProductionSiteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime>("ChangeDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasDatabaseName("UQ_PRODUCTION_SITES__ADDRESS");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_PRODUCTION_SITES__NAME");

                    b.ToTable("PRODUCTION_SITES", "REF");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref.Users.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<Guid>("PRODUCTION_SITE_UID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PRODUCTION_SITE_UID");

                    b.ToTable("USERS", "REF");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref.Warehouses.WarehouseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<DateTime>("ChangeDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("NAME");

                    b.Property<Guid>("PRODUCTION_SITE_UID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Uid1C")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID_1C");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_WAREHOUSES__NAME");

                    b.HasIndex("PRODUCTION_SITE_UID");

                    b.HasIndex("Uid1C")
                        .IsUnique()
                        .HasDatabaseName("UQ_WAREHOUSES__UID_1C");

                    b.ToTable("WAREHOUSES", "REF");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref1C.Boxes.BoxEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<DateTime>("ChangeDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("NAME");

                    b.Property<decimal>("Weight")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal(4,3)")
                        .HasColumnName("WEIGHT");

                    b.HasKey("Id");

                    b.ToTable("BOXES", "REF_1C");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref1C.Brands.BrandEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<DateTime>("ChangeDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_BRANDS__NAME");

                    b.ToTable("BRANDS", "REF_1C");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref1C.Bundles.BundleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<DateTime>("ChangeDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("NAME");

                    b.Property<decimal>("Weight")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal(4,3)")
                        .HasColumnName("WEIGHT");

                    b.HasKey("Id");

                    b.ToTable("BUNDLES", "REF_1C");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref1C.Characteristics.CharacteristicEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BOX_UID");

                    b.Property<short>("BundleCount")
                        .HasColumnType("smallint")
                        .HasColumnName("BUNDLE_COUNT");

                    b.Property<DateTime>("ChangeDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("NAME");

                    b.Property<Guid>("PluId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PLU_UID");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.HasIndex("PluId", "BoxId", "BundleCount")
                        .IsUnique()
                        .HasDatabaseName("UQ_CHARACTERISTICS__UNIQ");

                    b.ToTable("CHARACTERISTICS", "REF_1C");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref1C.Clips.ClipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<DateTime>("ChangeDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("NAME");

                    b.Property<decimal>("Weight")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal(4,3)")
                        .HasColumnName("WEIGHT");

                    b.HasKey("Id");

                    b.ToTable("CLIPS", "REF_1C");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref1C.Nestings.NestingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BOX_UID");

                    b.Property<short>("BundleCount")
                        .HasColumnType("smallint")
                        .HasColumnName("BUNDLE_COUNT");

                    b.Property<DateTime>("ChangeDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.ToTable("NESTINGS", "REF_1C");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref1C.Plus.PluEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BRAND_UID");

                    b.Property<Guid>("BundleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BUNDLE_UID");

                    b.Property<DateTime>("ChangeDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("ClipId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CLIP_UID");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Ean13")
                        .IsRequired()
                        .HasColumnType("varchar(13)")
                        .HasColumnName("EAN_13");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("FULL_NAME");

                    b.Property<bool>("IsWeight")
                        .HasColumnType("bit")
                        .HasColumnName("IS_WEIGHT");

                    b.Property<string>("Itf14")
                        .IsRequired()
                        .HasColumnType("varchar(14)")
                        .HasColumnName("ITF_14");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NAME");

                    b.Property<short>("Number")
                        .HasColumnType("smallint")
                        .HasColumnName("NUMBER");

                    b.Property<short>("ShelfLifeDays")
                        .HasColumnType("smallint")
                        .HasColumnName("SHELF_LIFE_DAYS");

                    b.Property<string>("StorageMethod")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("STORAGE_METHOD");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TEMPLATE_UID");

                    b.Property<decimal>("Weight")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal(4,3)")
                        .HasColumnName("WEIGHT");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("BundleId");

                    b.HasIndex("ClipId");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("UQ_PLUS__NUMBER");

                    b.HasIndex("TemplateId");

                    b.ToTable("PLUS", "REF_1C");
                });

            modelBuilder.Entity("Ws.Database.Entities.Zpl.StorageMethods.StorageMethodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<DateTime>("ChangeDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("NAME");

                    b.Property<string>("Zpl")
                        .IsRequired()
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("ZPL");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_STORAGE_METHODS__NAME");

                    b.ToTable("STORAGE_METHODS", "ZPL");
                });

            modelBuilder.Entity("Ws.Database.Entities.Zpl.Templates.TemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<string>("BarcodeBottomBody")
                        .IsRequired()
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("BARCODE_BOTTOM_BODY");

                    b.Property<string>("BarcodeRightBody")
                        .IsRequired()
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("BARCODE_RIGHT_BODY");

                    b.Property<string>("BarcodeTopBody")
                        .IsRequired()
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("BARCODE_TOP_BODY");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("BODY");

                    b.Property<DateTime>("ChangeDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<short>("Height")
                        .HasColumnType("smallint")
                        .HasColumnName("HEIGHT");

                    b.Property<bool>("IsWeight")
                        .HasColumnType("bit")
                        .HasColumnName("IS_WEIGHT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("NAME");

                    b.Property<short>("Width")
                        .HasColumnType("smallint")
                        .HasColumnName("WIDTH");

                    b.HasKey("Id");

                    b.HasIndex("Name", "IsWeight")
                        .IsUnique()
                        .HasDatabaseName("UQ_TEMPLATES__NAME__IS_WEIGHT");

                    b.ToTable("TEMPLATES", "ZPL");
                });

            modelBuilder.Entity("Ws.Database.Entities.Zpl.ZplResources.ZplResourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UID");

                    b.Property<DateTime>("ChangeDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("CreateDt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("NAME");

                    b.Property<string>("Zpl")
                        .IsRequired()
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("ZPL");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_RESOURCES__NAME");

                    b.ToTable("RESOURCES", "ZPL");
                });

            modelBuilder.Entity("Ws.Database.Views.Diag.DatabaseTables.DatabaseTableView", b =>
                {
                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FILE_NAME");

                    b.Property<int>("Rows")
                        .HasColumnType("int")
                        .HasColumnName("ROWS_COUNT");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SCHEMA");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TABLE");

                    b.Property<int>("UsedMb")
                        .HasColumnType("int")
                        .HasColumnName("USED_MB");

                    b.ToTable((string)null);

                    b.ToView("DATABASE_TABLES_VIEW", "DIAG");
                });

            modelBuilder.Entity("ARMS_PLUS_FK", b =>
                {
                    b.HasOne("Ws.Database.Entities.Ref.Lines.LineEntity", null)
                        .WithMany()
                        .HasForeignKey("ARM_UID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ARMS_PLUS__ARM");

                    b.HasOne("Ws.Database.Entities.Ref1C.Plus.PluEntity", null)
                        .WithMany()
                        .HasForeignKey("PLU_UID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ARMS_PLUS__PLU");
                });

            modelBuilder.Entity("Ws.Database.Entities.Print.Labels.LabelEntity", b =>
                {
                    b.HasOne("Ws.Database.Entities.Ref.Lines.LineEntity", "Line")
                        .WithMany()
                        .HasForeignKey("ARM_UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LABELS__ARM");

                    b.HasOne("Ws.Database.Entities.Ref1C.Plus.PluEntity", "Plu")
                        .WithMany()
                        .HasForeignKey("PLU_UID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LABELS__PLU");

                    b.HasOne("Ws.Database.Entities.Print.Pallets.PalletEntity", null)
                        .WithMany()
                        .HasForeignKey("PalletEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LABELS__PALLET");

                    b.Navigation("Line");

                    b.Navigation("Plu");
                });

            modelBuilder.Entity("Ws.Database.Entities.Print.Pallets.PalletEntity", b =>
                {
                    b.HasOne("Ws.Database.Entities.Ref.Lines.LineEntity", "Arm")
                        .WithMany()
                        .HasForeignKey("ARM_UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PALLETS__ARM");

                    b.HasOne("Ws.Database.Entities.Ref.PalletMen.PalletManEntity", "PalletMan")
                        .WithMany()
                        .HasForeignKey("PALLET_MAN_UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PALLETS__PALLET_MAN");

                    b.Navigation("Arm");

                    b.Navigation("PalletMan");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref.Lines.LineEntity", b =>
                {
                    b.HasOne("Ws.Database.Entities.Ref.Printers.PrinterEntity", "Printer")
                        .WithMany()
                        .HasForeignKey("PRINTER_UID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ARMS__PRINTER");

                    b.HasOne("Ws.Database.Entities.Ref.Warehouses.WarehouseEntity", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WAREHOUSE_UID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ARMS__WAREHOUSE");

                    b.Navigation("Printer");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref.PalletMen.PalletManEntity", b =>
                {
                    b.HasOne("Ws.Database.Entities.Ref.Warehouses.WarehouseEntity", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WAREHOUSE_UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PALLET_MEN__WAREHOUSE");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref.Printers.PrinterEntity", b =>
                {
                    b.HasOne("Ws.Database.Entities.Ref.ProductionSites.ProductionSiteEntity", "ProductionSite")
                        .WithMany()
                        .HasForeignKey("PRODUCTION_SITE_UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PALLET_MEN__PRODUCTION_SITE");

                    b.Navigation("ProductionSite");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref.Users.UserEntity", b =>
                {
                    b.HasOne("Ws.Database.Entities.Ref.ProductionSites.ProductionSiteEntity", "ProductionSite")
                        .WithMany()
                        .HasForeignKey("PRODUCTION_SITE_UID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_USERS__PRODUCTION_SITE");

                    b.Navigation("ProductionSite");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref.Warehouses.WarehouseEntity", b =>
                {
                    b.HasOne("Ws.Database.Entities.Ref.ProductionSites.ProductionSiteEntity", "ProductionSite")
                        .WithMany()
                        .HasForeignKey("PRODUCTION_SITE_UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WAREHOUSES__PRODUCTION_SITE");

                    b.Navigation("ProductionSite");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref1C.Characteristics.CharacteristicEntity", b =>
                {
                    b.HasOne("Ws.Database.Entities.Ref1C.Boxes.BoxEntity", "Box")
                        .WithMany()
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CHARACTERISTICS__BOX");

                    b.HasOne("Ws.Database.Entities.Ref1C.Plus.PluEntity", null)
                        .WithMany()
                        .HasForeignKey("PluId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CHARACTERISTICS__PLU");

                    b.Navigation("Box");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref1C.Nestings.NestingEntity", b =>
                {
                    b.HasOne("Ws.Database.Entities.Ref1C.Boxes.BoxEntity", "Box")
                        .WithMany()
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NESTINGS__BOX");

                    b.HasOne("Ws.Database.Entities.Ref1C.Plus.PluEntity", null)
                        .WithOne()
                        .HasForeignKey("Ws.Database.Entities.Ref1C.Nestings.NestingEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");
                });

            modelBuilder.Entity("Ws.Database.Entities.Ref1C.Plus.PluEntity", b =>
                {
                    b.HasOne("Ws.Database.Entities.Ref1C.Brands.BrandEntity", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PLUS__BRAND");

                    b.HasOne("Ws.Database.Entities.Ref1C.Bundles.BundleEntity", "Bundle")
                        .WithMany()
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PLUS__BUNDLE");

                    b.HasOne("Ws.Database.Entities.Ref1C.Clips.ClipEntity", "Clip")
                        .WithMany()
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PLUS__CLIP");

                    b.HasOne("Ws.Database.Entities.Zpl.Templates.TemplateEntity", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .HasConstraintName("FK_PLUS__TEMPLATE");

                    b.Navigation("Brand");

                    b.Navigation("Bundle");

                    b.Navigation("Clip");
                });
#pragma warning restore 612, 618
        }
    }
}
