global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Drawing;
global using System.Globalization;
global using System.Linq;
global using System.Management;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls.Primitives;
global using System.Windows.Data;
global using System.Windows.Input;
global using System.Xml;
global using PrinterCore.Tsc;
global using MDSoft.NetUtils;
global using MDSoft.WinFormsUtils;
global using MDSoft.Wmi.Enums;
global using MDSoft.Wmi.Models;
global using MvvmHelpers;
global using Nito.AsyncEx;
global using SuperSimpleTcp;
global using WsDataCore.Common;
global using WsDataCore.Enums;
global using WsDataCore.Helpers;
global using WsDataCore.Memory;
global using WsDataCore.Models;
global using WsLabelCore.Common;
global using WsLabelCore.Controls;
global using WsLabelCore.Helpers;
global using WsLabelCore.Models;
global using WsLabelCore.Pages;
global using WsLabelCore.Utils;
global using WsLabelCore.ViewModels;
global using WsLocalizationCore.Common;
global using WsLocalizationCore.Models;
global using WsLocalizationCore.Utils;
global using WsMassaCore.Enums;
global using WsMassaCore.Helpers;
global using WsMassaCore.Models;
global using Ws.StorageCore.Helpers;
global using Ws.StorageCore.Models;
global using Ws.StorageCore.Utils;
global using Ws.StorageCore.Views.ViewRefModels.PluLines;
global using Ws.StorageCore.Views.ViewRefModels.PluNestings;
global using FontStyle = System.Drawing.FontStyle;
global using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
global using Binding = System.Windows.Data.Binding;
global using Label = System.Windows.Forms.Label;
global using KeyEventArgs = System.Windows.Input.KeyEventArgs;