//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScalesDesktop.Source.Shared.Localization {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResources_en_US {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources_en_US() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScalesDesktop.Source.Shared.Localization.ApplicationResources.en-US", typeof(ApplicationResources_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Print all.
        /// </summary>
        internal static string BtnAllLabelsPrinting {
            get {
                return ResourceManager.GetString("BtnAllLabelsPrinting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available in.
        /// </summary>
        internal static string BtnCooldown {
            get {
                return ResourceManager.GetString("BtnCooldown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string BtnCreate {
            get {
                return ResourceManager.GetString("BtnCreate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string BtnEnter {
            get {
                return ResourceManager.GetString("BtnEnter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Print label.
        /// </summary>
        internal static string BtnLabelPrint {
            get {
                return ResourceManager.GetString("BtnLabelPrint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string BtnLogIn {
            get {
                return ResourceManager.GetString("BtnLogIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Print PC.
        /// </summary>
        internal static string BtnPrintPC {
            get {
                return ResourceManager.GetString("BtnPrintPC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Calibrate scale.
        /// </summary>
        internal static string BtnScaleCalibration {
            get {
                return ResourceManager.GetString("BtnScaleCalibration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Print selected.
        /// </summary>
        internal static string BtnSelectedLabelsPrinting {
            get {
                return ResourceManager.GetString("BtnSelectedLabelsPrinting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create pallet form.
        /// </summary>
        internal static string CreatePalletFormHeader {
            get {
                return ResourceManager.GetString("CreatePalletFormHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select PLU.
        /// </summary>
        internal static string DisplayPluSelectWarning {
            get {
                return ResourceManager.GetString("DisplayPluSelectWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scales are disconnected.
        /// </summary>
        internal static string DisplayScalesDisconnectedWarning {
            get {
                return ResourceManager.GetString("DisplayScalesDisconnectedWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To create a new pallet, click the button at the top of the left block.
        /// </summary>
        internal static string FuncCardCreationDescription {
            get {
                return ResourceManager.GetString("FuncCardCreationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        internal static string FuncCardCreationTitle {
            get {
                return ResourceManager.GetString("FuncCardCreationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description of the main functionality of the application.
        /// </summary>
        internal static string FuncCardDescription {
            get {
                return ResourceManager.GetString("FuncCardDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Functional.
        /// </summary>
        internal static string FuncCardHeader {
            get {
                return ResourceManager.GetString("FuncCardHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To print labels, select a pallet. In the Labels tab, you can print all the labels, or select the ones you need in the table and click.
        /// </summary>
        internal static string FuncCardLabelPrintingDescription {
            get {
                return ResourceManager.GetString("FuncCardLabelPrintingDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Label printing.
        /// </summary>
        internal static string FuncCardLabelPrintingTitle {
            get {
                return ResourceManager.GetString("FuncCardLabelPrintingTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To print a pallet card, select the pallet and go to the Information tab, then click.
        /// </summary>
        internal static string FuncCardPCPrintingDescription {
            get {
                return ResourceManager.GetString("FuncCardPCPrintingDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pallet card printing.
        /// </summary>
        internal static string FuncCardPCPrintingTitle {
            get {
                return ResourceManager.GetString("FuncCardPCPrintingTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To view information about the pallet, select the desired pallet in the left block.
        /// </summary>
        internal static string FuncCardViewingDescription {
            get {
                return ResourceManager.GetString("FuncCardViewingDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Viewing.
        /// </summary>
        internal static string FuncCardViewingTitle {
            get {
                return ResourceManager.GetString("FuncCardViewingTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the kneading.
        /// </summary>
        internal static string KneadingInputPlaceholder {
            get {
                return ResourceManager.GetString("KneadingInputPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PLU config.
        /// </summary>
        internal static string LabelConfigHeader {
            get {
                return ResourceManager.GetString("LabelConfigHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a label count.
        /// </summary>
        internal static string LabelCountInputPlaceholder {
            get {
                return ResourceManager.GetString("LabelCountInputPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nesting is not selected.
        /// </summary>
        internal static string NestingSelectPlaceholder {
            get {
                return ResourceManager.GetString("NestingSelectPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log in to your account.
        /// </summary>
        internal static string PalletManFormHeader {
            get {
                return ResourceManager.GetString("PalletManFormHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No pallets found.
        /// </summary>
        internal static string PalletSelectEmpty {
            get {
                return ResourceManager.GetString("PalletSelectEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the pallet weight.
        /// </summary>
        internal static string TrayWeightInputPlaceholder {
            get {
                return ResourceManager.GetString("TrayWeightInputPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the password.
        /// </summary>
        internal static string PasswordInputPlaceholder {
            get {
                return ResourceManager.GetString("PasswordInputPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PLU select.
        /// </summary>
        internal static string PluSelectHeader {
            get {
                return ResourceManager.GetString("PluSelectHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PLU is not selected.
        /// </summary>
        internal static string PluSelectPlaceholder {
            get {
                return ResourceManager.GetString("PluSelectPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The printer head is opened.
        /// </summary>
        internal static string PrinterStatusHeadOpen {
            get {
                return ResourceManager.GetString("PrinterStatusHeadOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The printer is deactivated.
        /// </summary>
        internal static string PrinterStatusIsDisabled {
            get {
                return ResourceManager.GetString("PrinterStatusIsDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The printer is offline.
        /// </summary>
        internal static string PrinterStatusIsForceDisconnected {
            get {
                return ResourceManager.GetString("PrinterStatusIsForceDisconnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The label is stuck in the printer.
        /// </summary>
        internal static string PrinterStatusPaperJam {
            get {
                return ResourceManager.GetString("PrinterStatusPaperJam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The printer has run out of tape.
        /// </summary>
        internal static string PrinterStatusPaperOut {
            get {
                return ResourceManager.GetString("PrinterStatusPaperOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The printer is on pause.
        /// </summary>
        internal static string PrinterStatusPaused {
            get {
                return ResourceManager.GetString("PrinterStatusPaused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown printer error.
        /// </summary>
        internal static string PrinterStatusUnknown {
            get {
                return ResourceManager.GetString("PrinterStatusUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The scales lack the necessary weight..
        /// </summary>
        internal static string ScalesStatusTooLight {
            get {
                return ResourceManager.GetString("ScalesStatusTooLight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The scales are not stable.
        /// </summary>
        internal static string ScalesStatusUnstable {
            get {
                return ResourceManager.GetString("ScalesStatusUnstable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search by number.
        /// </summary>
        internal static string SearchByNumberPlaceholder {
            get {
                return ResourceManager.GetString("SearchByNumberPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select your user.
        /// </summary>
        internal static string UserSelectPlaceholder {
            get {
                return ResourceManager.GetString("UserSelectPlaceholder", resourceCulture);
            }
        }
    }
}
