-- «¿ ¿«€.
-- ¬≈–—»ﬂ 0.0.10
USE [SCALESDB]
SELECT
	 [DB_SCALES].[ORDERS].[ID]
	,[DB_SCALES].[ORDERS].[ORDERTYPE]
	,[DB_SCALES].[ORDERS].[PRODUCTDATE]
	,[DB_SCALES].[ORDERS].[PLANEBOXCOUNT]
	,[DB_SCALES].[ORDERS].[PLANEPALLETCOUNT]
	,[DB_SCALES].[ORDERS].[PLANEPACKINGOPERATIONBEGINDATE]
	,[DB_SCALES].[ORDERS].[PLANEPACKINGOPERATIONENDDATE]
	,[DB_SCALES].[ORDERS].[1—SCALEID]
	,[DB_SCALES].[ORDERS].[PLU]
	,[DB_SCALES].[ORDERS].[1CRREFID]
	,[DB_SCALES].[ORDERS].[TEMPLATEID]
	,[DB_SCALES].[ORDERS].[CREATEDATE]
	,[DB_SCALES].[ORDERS].[MODIFIEDDATE]
FROM [DB_SCALES].[ORDERS]
ORDER BY [DB_SCALES].[ORDERS].[ID]
