USE [SCALESDB]
DECLARE @GUID NVARCHAR(255) = '7B832E43-BAA4-11EA-BC3C-AC1F6B02AD52'
-- онхяй GUID вепег рюакхжс.
-- бепяхъ 0.0.10.
IF EXISTS (SELECT 1 FROM [DB_SCALES].[SCALES] WHERE [DB_SCALES].[SCALES].[IDRREF] = @GUID)
	SELECT 'TRUE' [RESULT]
ELSE
	SELECT 'FALSE' [RESULT]

-- онхяй GUID вепег тсмйжхч.
-- бепяхъ 0.0.10.
SELECT * FROM [DB_SCALES].[GETSCALEBYID] (@GUID)
