global using System;
global using System.Collections.Generic;
global using System.Drawing;
global using System.Drawing.Imaging;
global using System.IO;
global using System.Linq;
global using System.Net.Sockets;
global using System.Runtime.InteropServices;
global using System.Text;