GET https://localhost:5138/api/production-sites

###


POST https://localhost:5138/api/production-sites
Content-Type: application/json

{
    "name": "Площадка Камешковоооо",
    "address": "dawdadwdaw"
}