GET https://scales-api-dev.kolbasa-vs.local/api/device-control/production-sites/ffffffff-ffff-ffff-ffff-ffffffffffff

###

POST https://localhost:5138/api/warehouses
Content-Type: application/json

{
    "name": "Площадка Камешковоооо",
    "id1C": "ffffffff-ffff-ffff-ffff-ffffffffffff",
    "productionSiteId": "ffffffff-ffff-ffff-ffff-ffffffffffff"
}

###

POST https://localhost:5138/api/warehouses/6ced6c1e-7b94-46c1-5493-08dcabbe3249
Content-Type: application/json

{
    "name": "Площадка Камешковооооsss",
    "id1C": "ffffffff-ffff-ffff-ffff-ffffffffffff"
}