global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Drawing;
global using System.Globalization;
global using System.Linq;
global using System.Management;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls.Primitives;
global using System.Windows.Data;
global using System.Windows.Input;
global using System.Xml;
global using Ws.PrinterCore.Tsc;
global using MDSoft.NetUtils;
global using MDSoft.WinFormsUtils;
global using MDSoft.Wmi.Enums;
global using MDSoft.Wmi.Models;
global using MvvmHelpers;
global using Nito.AsyncEx;
global using SuperSimpleTcp;
global using Ws.DataCore.Common;
global using Ws.DataCore.Enums;
global using Ws.DataCore.Helpers;
global using Ws.DataCore.Models;
global using Ws.LabelCore.Common;
global using Ws.LabelCore.Controls;
global using Ws.LabelCore.Helpers;
global using Ws.LabelCore.Models;
global using Ws.LabelCore.Pages;
global using Ws.LabelCore.Utils;
global using Ws.LabelCore.ViewModels;
global using WsLocalizationCore.Common;
global using WsLocalizationCore.Models;
global using WsLocalizationCore.Utils;
global using Ws.MassaCore.Enums;
global using Ws.MassaCore.Helpers;
global using Ws.MassaCore.Models;
global using Ws.StorageCore.Helpers;
global using Ws.StorageCore.Models;
global using Ws.StorageCore.Utils;
global using Ws.StorageCore.Views.ViewRefModels.PluLines;
global using Ws.StorageCore.Views.ViewRefModels.PluNestings;
global using FontStyle = System.Drawing.FontStyle;
global using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
global using Binding = System.Windows.Data.Binding;
global using Label = System.Windows.Forms.Label;
global using KeyEventArgs = System.Windows.Input.KeyEventArgs;