global using System;
global using System.Collections.Generic;
global using System.Linq;
global using WsPrintCore.Zpl;
global using WsStorageCore.Models;
global using WsStorageCore.Tables.TableScaleModels.TemplatesResources;
global using WsStorageCore.Utils;
global using Zebra.Sdk.Comm;
global using Zebra.Sdk.Printer;
global using ZebraPrinterStatus = Zebra.Sdk.Printer.PrinterStatus;