//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScalesHybrid.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResources_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScalesHybrid.Resources.ApplicationResources.en-US", typeof(ApplicationResources_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string ButtonCalculatorEnter {
            get {
                return ResourceManager.GetString("ButtonCalculatorEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print label.
        /// </summary>
        internal static string ButtonLabelPrint {
            get {
                return ResourceManager.GetString("ButtonLabelPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change line.
        /// </summary>
        internal static string ButtonLineChange {
            get {
                return ResourceManager.GetString("ButtonLineChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set kneading.
        /// </summary>
        internal static string ButtonPalletPage {
            get {
                return ResourceManager.GetString("ButtonPalletPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PLU.
        /// </summary>
        internal static string ButtonPLUChange {
            get {
                return ResourceManager.GetString("ButtonPLUChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PLU nesting.
        /// </summary>
        internal static string ButtonPLUNestingChange {
            get {
                return ResourceManager.GetString("ButtonPLUNestingChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate scale.
        /// </summary>
        internal static string ButtonScaleCalibration {
            get {
                return ResourceManager.GetString("ButtonScaleCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Select.
        /// </summary>
        internal static string DialogLineSelectHeaderLabel {
            get {
                return ResourceManager.GetString("DialogLineSelectHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DialogLineSelectNameColumn {
            get {
                return ResourceManager.GetString("DialogLineSelectNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string DialogLineSelectNumberColumn {
            get {
                return ResourceManager.GetString("DialogLineSelectNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        internal static string DialogLineSelectWorkshopColumn {
            get {
                return ResourceManager.GetString("DialogLineSelectWorkshopColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box weight.
        /// </summary>
        internal static string DialogNestingSelectBoxWeightColumn {
            get {
                return ResourceManager.GetString("DialogNestingSelectBoxWeightColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle count.
        /// </summary>
        internal static string DialogNestingSelectBundleCountColumn {
            get {
                return ResourceManager.GetString("DialogNestingSelectBundleCountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle weight.
        /// </summary>
        internal static string DialogNestingSelectBundleWeightColumn {
            get {
                return ResourceManager.GetString("DialogNestingSelectBundleWeightColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default.
        /// </summary>
        internal static string DialogNestingSelectDefaultColumn {
            get {
                return ResourceManager.GetString("DialogNestingSelectDefaultColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesting Select.
        /// </summary>
        internal static string DialogNestingSelectHeaderLabel {
            get {
                return ResourceManager.GetString("DialogNestingSelectHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DialogNestingSelectNameColumn {
            get {
                return ResourceManager.GetString("DialogNestingSelectNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tare weight.
        /// </summary>
        internal static string DialogNestingSelectTareWeightColumn {
            get {
                return ResourceManager.GetString("DialogNestingSelectTareWeightColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLU Select.
        /// </summary>
        internal static string DialogPluSelectHeaderLabel {
            get {
                return ResourceManager.GetString("DialogPluSelectHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DialogPluSelectNameColumn {
            get {
                return ResourceManager.GetString("DialogPluSelectNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string DialogPluSelectNumberColumn {
            get {
                return ResourceManager.GetString("DialogPluSelectNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string DialogPluSelectTypeColumn {
            get {
                return ResourceManager.GetString("DialogPluSelectTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label print.
        /// </summary>
        internal static string PageTitleIndex {
            get {
                return ResourceManager.GetString("PageTitleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLU Select.
        /// </summary>
        internal static string PageTitlePluSelect {
            get {
                return ResourceManager.GetString("PageTitlePluSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ProductDisplayDateLabel {
            get {
                return ResourceManager.GetString("ProductDisplayDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kneading.
        /// </summary>
        internal static string ProductDisplayKneadingLabel {
            get {
                return ResourceManager.GetString("ProductDisplayKneadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle count.
        /// </summary>
        internal static string ProductDisplayNestingCount {
            get {
                return ResourceManager.GetString("ProductDisplayNestingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesting.
        /// </summary>
        internal static string ProductDisplayNestingLabel {
            get {
                return ResourceManager.GetString("ProductDisplayNestingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net weight.
        /// </summary>
        internal static string ProductDisplayNetWeightLabel {
            get {
                return ResourceManager.GetString("ProductDisplayNetWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tare weight.
        /// </summary>
        internal static string ProductDisplayTareWeightLabel {
            get {
                return ResourceManager.GetString("ProductDisplayTareWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PLU.
        /// </summary>
        internal static string ProductDisplayWarningPluSelect {
            get {
                return ResourceManager.GetString("ProductDisplayWarningPluSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scales are disconnected.
        /// </summary>
        internal static string ProductDisplayWarningScalesDisconnected {
            get {
                return ResourceManager.GetString("ProductDisplayWarningScalesDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight is stabilizing.
        /// </summary>
        internal static string ScaleStabilization {
            get {
                return ResourceManager.GetString("ScaleStabilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        internal static string WeightMeasureKilogram {
            get {
                return ResourceManager.GetString("WeightMeasureKilogram", resourceCulture);
            }
        }
    }
}
