//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScalesHybrid.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResources_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScalesHybrid.Resources.ApplicationResources.en-US", typeof(ApplicationResources_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set kneading.
        /// </summary>
        internal static string ButtonKneadingChange {
            get {
                return ResourceManager.GetString("ButtonKneadingChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print label.
        /// </summary>
        internal static string ButtonLabelPrint {
            get {
                return ResourceManager.GetString("ButtonLabelPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change line.
        /// </summary>
        internal static string ButtonLineChange {
            get {
                return ResourceManager.GetString("ButtonLineChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PLU.
        /// </summary>
        internal static string ButtonPLUChange {
            get {
                return ResourceManager.GetString("ButtonPLUChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PLU nesting.
        /// </summary>
        internal static string ButtonPLUNestingChange {
            get {
                return ResourceManager.GetString("ButtonPLUNestingChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open scale terminal.
        /// </summary>
        internal static string ButtonScaleTerminal {
            get {
                return ResourceManager.GetString("ButtonScaleTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string KneadingDisplayDateLabel {
            get {
                return ResourceManager.GetString("KneadingDisplayDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kneading.
        /// </summary>
        internal static string KneadingDisplayKneadingLabel {
            get {
                return ResourceManager.GetString("KneadingDisplayKneadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string KneadingDisplayWeightLabel {
            get {
                return ResourceManager.GetString("KneadingDisplayWeightLabel", resourceCulture);
            }
        }
    }
}
