//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceControl2.Source.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResources_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviceControl2.Source.Shared.Localization.ApplicationResources.en-US", typeof(ApplicationResources_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device control.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string BtnSubmit {
            get {
                return ResourceManager.GetString("BtnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DataGridContextMenuDelete {
            get {
                return ResourceManager.GetString("DataGridContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in a dialog.
        /// </summary>
        internal static string DataGridContextMenuOpenInDialog {
            get {
                return ResourceManager.GetString("DataGridContextMenuOpenInDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new tab.
        /// </summary>
        internal static string DataGridContextMenuOpenInNewTab {
            get {
                return ResourceManager.GetString("DataGridContextMenuOpenInNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        internal static string DataGridTotalItems {
            get {
                return ResourceManager.GetString("DataGridTotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string FormActionDelete {
            get {
                return ResourceManager.GetString("FormActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string FormActionLock {
            get {
                return ResourceManager.GetString("FormActionLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relogin.
        /// </summary>
        internal static string FormActionRelogin {
            get {
                return ResourceManager.GetString("FormActionRelogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string FormActionReset {
            get {
                return ResourceManager.GetString("FormActionReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string FormActionShare {
            get {
                return ResourceManager.GetString("FormActionShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string FormActionsTitle {
            get {
                return ResourceManager.GetString("FormActionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string FormActionUnlock {
            get {
                return ResourceManager.GetString("FormActionUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string FormEmptyItemPlaceholder {
            get {
                return ResourceManager.GetString("FormEmptyItemPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer control.
        /// </summary>
        internal static string FormPrinterControl {
            get {
                return ResourceManager.GetString("FormPrinterControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the printer.
        /// </summary>
        internal static string FormPrinterDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormPrinterDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the production site.
        /// </summary>
        internal static string FormProductionSiteDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormProductionSiteDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        internal static string FormSelectEmptyDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormSelectEmptyDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string FormSelectSearchDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormSelectSearchDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the warehouse.
        /// </summary>
        internal static string FormWarehouseDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormWarehouseDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the menu section to continue.
        /// </summary>
        internal static string HomeMsgDescription {
            get {
                return ResourceManager.GetString("HomeMsgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value....
        /// </summary>
        internal static string InputDefaultPlaceholder {
            get {
                return ResourceManager.GetString("InputDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while converting zpl code to image.
        /// </summary>
        internal static string LabelsPreviewErrorMsg {
            get {
                return ResourceManager.GetString("LabelsPreviewErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image.
        /// </summary>
        internal static string LabelsPreviewNoData {
            get {
                return ResourceManager.GetString("LabelsPreviewNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string LabelsPreviewTitle {
            get {
                return ResourceManager.GetString("LabelsPreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1C References.
        /// </summary>
        internal static string Menu1CReferences {
            get {
                return ResourceManager.GetString("Menu1CReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string MenuAdministration {
            get {
                return ResourceManager.GetString("MenuAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string MenuDevices {
            get {
                return ResourceManager.GetString("MenuDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        internal static string MenuDiagnostics {
            get {
                return ResourceManager.GetString("MenuDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string MenuOperations {
            get {
                return ResourceManager.GetString("MenuOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print settings.
        /// </summary>
        internal static string MenuPrintSettings {
            get {
                return ResourceManager.GetString("MenuPrintSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        internal static string MenuReferences {
            get {
                return ResourceManager.GetString("MenuReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer version.
        /// </summary>
        internal static string NavMenuDeveloperVersion {
            get {
                return ResourceManager.GetString("NavMenuDeveloperVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1C Logs.
        /// </summary>
        internal static string Section1CLogs {
            get {
                return ResourceManager.GetString("Section1CLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agg. labels.
        /// </summary>
        internal static string SectionAggregatedLabels {
            get {
                return ResourceManager.GetString("SectionAggregatedLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps logs.
        /// </summary>
        internal static string SectionAppsLogs {
            get {
                return ResourceManager.GetString("SectionAppsLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcodes.
        /// </summary>
        internal static string SectionBarcodes {
            get {
                return ResourceManager.GetString("SectionBarcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxes.
        /// </summary>
        internal static string SectionBoxes {
            get {
                return ResourceManager.GetString("SectionBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        internal static string SectionBrands {
            get {
                return ResourceManager.GetString("SectionBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundles.
        /// </summary>
        internal static string SectionBundles {
            get {
                return ResourceManager.GetString("SectionBundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clips.
        /// </summary>
        internal static string SectionClips {
            get {
                return ResourceManager.GetString("SectionClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string SectionDatabase {
            get {
                return ResourceManager.GetString("SectionDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string SectionLabels {
            get {
                return ResourceManager.GetString("SectionLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line PLU.
        /// </summary>
        internal static string SectionLinePLU {
            get {
                return ResourceManager.GetString("SectionLinePLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string SectionLines {
            get {
                return ResourceManager.GetString("SectionLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet Men.
        /// </summary>
        internal static string SectionPalletMen {
            get {
                return ResourceManager.GetString("SectionPalletMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLU.
        /// </summary>
        internal static string SectionPLU {
            get {
                return ResourceManager.GetString("SectionPLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nestrings.
        /// </summary>
        internal static string SectionPluNestings {
            get {
                return ResourceManager.GetString("SectionPluNestings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printers.
        /// </summary>
        internal static string SectionPrinters {
            get {
                return ResourceManager.GetString("SectionPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Sites.
        /// </summary>
        internal static string SectionProductionSites {
            get {
                return ResourceManager.GetString("SectionProductionSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string SectionRoles {
            get {
                return ResourceManager.GetString("SectionRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLU Storages.
        /// </summary>
        internal static string SectionStorageMethods {
            get {
                return ResourceManager.GetString("SectionStorageMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates Resources.
        /// </summary>
        internal static string SectionTemplateResources {
            get {
                return ResourceManager.GetString("SectionTemplateResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string SectionTemplates {
            get {
                return ResourceManager.GetString("SectionTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string SectionUsers {
            get {
                return ResourceManager.GetString("SectionUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions.
        /// </summary>
        internal static string SectionVersions {
            get {
                return ResourceManager.GetString("SectionVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouses.
        /// </summary>
        internal static string SectionWarehouses {
            get {
                return ResourceManager.GetString("SectionWarehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weightings.
        /// </summary>
        internal static string SectionWeightings {
            get {
                return ResourceManager.GetString("SectionWeightings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value copied to clipboard.
        /// </summary>
        internal static string ToastCopyToClipboard {
            get {
                return ResourceManager.GetString("ToastCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was created.
        /// </summary>
        internal static string ToastCreateItem {
            get {
                return ResourceManager.GetString("ToastCreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was deleted.
        /// </summary>
        internal static string ToastDeleteItem {
            get {
                return ResourceManager.GetString("ToastDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original values restored.
        /// </summary>
        internal static string ToastResetItem {
            get {
                return ResourceManager.GetString("ToastResetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was updated.
        /// </summary>
        internal static string ToastUpdateItem {
            get {
                return ResourceManager.GetString("ToastUpdateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url copied to clipboard.
        /// </summary>
        internal static string ToastUrlCopyToClipboard {
            get {
                return ResourceManager.GetString("ToastUrlCopyToClipboard", resourceCulture);
            }
        }
    }
}
