// Global using directives
global using BlazorCore.Models;
global using BlazorCore.Services;
global using BlazorCore.Utils;
global using BlazorDownloadFile;
global using DataCore;
global using DataCore.Localizations;
global using DataCore.Models;
global using DataCore.Protocols;
global using DataCore.Sql;
global using DataCore.Sql.Controllers;
global using DataCore.Sql.Models;
global using DataCore.Sql.Tables;
global using DataCore.Sql.TableScaleModels;
global using DataCore.Utils;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Forms;
global using MudBlazor;
global using Radzen;
global using System.Globalization;
global using System.Runtime.CompilerServices;
global using static DataCore.ShareEnums;
