

CREATE LOGIN [SsisUserRW] WITH PASSWORD=N'1q@W3e4r', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER [SsisUserRW] FOR LOGIN [SsisUserRW] WITH DEFAULT_SCHEMA=[db_scales]
GO

ALTER ROLE [db_datareader] ADD MEMBER [SsisUserRW]
GO

ALTER ROLE [db_datawriter] ADD MEMBER [SsisUserRW]
GO
